export interface CircuitCharacter {
  round: number;
  trackType: "Street" | "Permanent";
  overtaking: "Rare" | "Occasional" | "Frequent";
  overtakingNote: string;
  safetyCarLikelihood: "Low" | "Medium" | "High";
  safetyCarNote: string;
  poleToWinPct: number;
  poleToWinNote: string;
  insight: string;
  hasHistory: boolean;
  // ── Extended prediction intel (populated for remaining 2026 rounds) ──
  /** Short tyre-strategy badge, e.g. "1-stop", "1–2 stop", "2–3 stop". */
  tyreStops?: string;
  /** How tyres behave here and what it means for strategy. */
  tyreNote?: string;
  /** Typical conditions and rain/temperature risk for the weekend. */
  weatherNote?: string;
  /** What kind of car/driver this circuit rewards — the DNA of a winner here. */
  trackFavours?: string;
  /** Bottom-line takeaway: the single biggest factor to weigh when predicting. */
  predictionAngle?: string;
}

export const CIRCUIT_INTEL: CircuitCharacter[] = [
  {
    round: 1,
    trackType: "Permanent",
    overtaking: "Occasional",
    overtakingNote: "Turn 1 and Turn 9 chicane offer the best passing chances, but tyre delta is often needed.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "Walls are close at some corners and the field is bunched after the restart — incidents happen.",
    poleToWinPct: 60,
    poleToWinNote: "Pole converts to victory about 60% of the time; the long run to Turn 1 keeps challengers honest.",
    insight: "Albert Park hosted an F1 race for the first time in 1996, and Michael Schumacher won that inaugural event.",
    hasHistory: true,
  },
  {
    round: 2,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "Long straights into Turns 6 and 14 give DRS a full effect and generate multiple passes per lap.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "High-speed corners and a long back section create occasional contact, especially at the start.",
    poleToWinPct: 65,
    poleToWinNote: "Pole is valuable on the long run to Turn 1, giving pole sitters a strong conversion rate.",
    insight: "Shanghai hosted the first ever Chinese Grand Prix in 2004 — Michael Schumacher won that race too.",
    hasHistory: true,
  },
  {
    round: 3,
    trackType: "Permanent",
    overtaking: "Occasional",
    overtakingNote: "The Esses demand focus, not overtaking; Degner and the Spoon curve offer the real attack points.",
    safetyCarLikelihood: "Low",
    safetyCarNote: "Suzuka is wide and forgiving enough that big incidents are rare despite its fearsome reputation.",
    poleToWinPct: 70,
    poleToWinNote: "Qualifying pace is decisive — once through the Esses cleanly, a fast car is very hard to pass.",
    insight: "Suzuka is one of only two figure-eight circuits on the F1 calendar, with the overpass unique in motorsport.",
    hasHistory: true,
  },
  {
    round: 4,
    trackType: "Street",
    overtaking: "Occasional",
    overtakingNote: "Two DRS zones help, but the tight infield limits overtaking to Turn 1 and the final hairpin.",
    safetyCarLikelihood: "High",
    safetyCarNote: "Racing through a car park on a temporary circuit means the safety car makes multiple appearances most years.",
    poleToWinPct: 60,
    poleToWinNote: "Sprint weekend format shuffles the grid, often making the Sunday race more chaotic than pole suggests.",
    insight: "The Miami GP venue is built around Hard Rock Stadium — drivers actually race through a faux marina never used for boats.",
    hasHistory: true,
  },
  {
    round: 5,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "Multiple hairpins and a long pit straight with DRS create consistent overtaking opportunities.",
    safetyCarLikelihood: "High",
    safetyCarNote: "Unpredictable Montreal weather and the Wall of Champions claim victims almost every year.",
    poleToWinPct: 55,
    poleToWinNote: "Strategy and safety-car restarts regularly upset the running order, making pole less dominant.",
    insight: "The notorious 'Wall of Champions' at the final chicane has caught Damon Hill, Michael Schumacher, and Jacques Villeneuve.",
    hasHistory: true,
  },
  {
    round: 6,
    trackType: "Street",
    overtaking: "Rare",
    overtakingNote: "Monaco is the hardest circuit in the world to overtake on — strategy and qualifying almost entirely decide it.",
    safetyCarLikelihood: "High",
    safetyCarNote: "Any touch of the barrier brings out the safety car; a virtual safety car appears on the vast majority of Sundays.",
    poleToWinPct: 80,
    poleToWinNote: "Pole position is more valuable here than anywhere — Monaco is basically a time trial on Saturday.",
    insight: "Ayrton Senna won 6 Monaco GPs. His 1984 drive in the rain — before retirement — is considered his greatest lap.",
    hasHistory: true,
  },
  {
    round: 7,
    trackType: "Permanent",
    overtaking: "Occasional",
    overtakingNote: "The long DRS run down to Turn 1 and the final chicane are the main passing spots on this technical circuit.",
    safetyCarLikelihood: "Low",
    safetyCarNote: "Wide run-off areas and modern barriers keep incidents contained — safety cars are genuinely rare here.",
    poleToWinPct: 65,
    poleToWinNote: "Tyre management matters as much as raw pace — cars degrade heavily in the heat.",
    insight: "Barcelona was a key testing venue for decades, meaning teams knew every bump before the season even started.",
    hasHistory: true,
  },
  {
    round: 8,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "The short layout and multiple DRS zones make overtaking common, especially after safety-car restarts.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "High-speed corners and close racing create regular incidents, particularly in wet Austrian conditions.",
    poleToWinPct: 60,
    poleToWinNote: "DRS is very effective here; a quicker car can pass even from a few places back.",
    insight: "The Red Bull Ring is one of the shortest F1 circuits, meaning drivers complete more laps than anywhere else on the calendar.",
    hasHistory: true,
  },
  {
    round: 9,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "Copse, Maggotts and the Hangar straight all provide overtaking chances; British fans are treated to great racing.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "Changeable British weather can trigger incidents, and high-speed corners increase risk on the opening lap.",
    poleToWinPct: 60,
    poleToWinNote: "Strategy plays a significant role — tyre choices in variable conditions can completely change the result.",
    insight: "Silverstone hosted the very first Formula 1 World Championship race in 1950, making it F1's spiritual home.",
    hasHistory: true,
  },
  {
    round: 10,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "Raidillon-Kemmel and the Bus Stop chicane are both overtaking hotspots on this mega-fast circuit.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "Weather in the Ardennes changes rapidly — fog, rain, and poor visibility have forced red flags and delays.",
    poleToWinPct: 60,
    poleToWinNote: "Spa rewards pure downforce and power, so race pace can differ wildly depending on power unit spec.",
    insight: "Spa-Francorchamps is the longest circuit on the F1 calendar at 7.004 km per lap.",
    hasHistory: true,
  },
  {
    round: 11,
    trackType: "Permanent",
    overtaking: "Rare",
    overtakingNote: "The twisty, narrow Hungaroring offers very few clean passing opportunities — it's called the Monaco of permanent tracks.",
    safetyCarLikelihood: "Low",
    safetyCarNote: "Relatively modern surface and wide run-offs keep the safety car in the garage most Sundays.",
    poleToWinPct: 75,
    poleToWinNote: "Overtaking is so difficult that qualifying position can define the entire race outcome.",
    insight: "Hungary hosted the first F1 race behind the Iron Curtain in 1986, drawing 200,000 spectators.",
    hasHistory: true,
    tyreStops: "1–2 stop",
    tyreNote: "Relentless slow-to-medium corners load the front-left hard, and midsummer track temps push thermal degradation high. Teams often gamble on a 1-stop to protect track position, but a well-timed undercut is devastating here.",
    weatherNote: "Peak-summer heat with track temps regularly above 50°C, which amplifies deg. Isolated afternoon thunderstorms are the main wildcard and have flipped results before.",
    trackFavours: "Cars with strong high-downforce balance and gentle front-tyre usage. Qualifying one-lap pace matters more than raw race speed because clean air is gold.",
    predictionAngle: "Track position is everything — start from your quali prediction. Whoever takes pole is the strong favourite, and the undercut means the driver stopping first often jumps those ahead. Rain is the only realistic script-flipper.",
  },
  {
    round: 12,
    trackType: "Permanent",
    overtaking: "Occasional",
    overtakingNote: "Tarzanbocht hairpin and the final chicane see most passes, though wind direction can change everything.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "Sand blown onto the track from the dunes and unpredictable sea wind cause frequent incidents.",
    poleToWinPct: 65,
    poleToWinNote: "Zandvoort is tight and fast; once settled, leading cars rarely face serious pressure.",
    insight: "Zandvoort was absent from the F1 calendar for 35 years before returning as the Dutch GP home in 2021.",
    hasHistory: true,
    tyreStops: "1–2 stop",
    tyreNote: "The banked final corner and Turn 3 put huge lateral energy through the tyres, so degradation is higher than the short lap suggests. Most run a 1-stop, but a Sprint weekend eats into practice data and can force reactive strategy.",
    weatherNote: "A North Sea coastal circuit — wind direction swings lap times and balance, and sea-fog or sudden rain showers are a genuine risk. Sand blown onto the racing line hurts early-session grip.",
    trackFavours: "Well-balanced, high-downforce cars that can put temperature into the tyres quickly. Confidence through the banked corners separates the front-runners.",
    predictionAngle: "This is a Sprint weekend, so points and grid slots come from two races with minimal practice — expect strategy noise. The track is narrow and passing is hard, so weight qualifying heavily, then factor a real chance of weather chaos.",
  },
  {
    round: 13,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "Monza has the highest top speeds in F1; the long straights and chicanes generate huge slipstreaming battles.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "The chicanes cause contact at high approach speeds, and tyre failures are a historical risk.",
    poleToWinPct: 55,
    poleToWinNote: "Slipstreaming means the lead changes multiple times per lap; qualifying matters but race pace and strategy rule.",
    insight: "Monza is the fastest circuit in F1, regularly seeing average race speeds above 260 km/h.",
    hasHistory: true,
    tyreStops: "1-stop",
    tyreNote: "Skinny low-downforce wings mean low cornering loads and one of the gentlest tyre-wear circuits of the year — a straightforward 1-stop is the norm, so strategy variance is low unless a safety car intervenes.",
    weatherNote: "Early-September northern Italy is usually warm and dry, but the Monza area is prone to sharp thunderstorms that have repeatedly thrown qualifying and races into chaos.",
    trackFavours: "Low-drag, powerful cars with strong straight-line speed and stable braking into the chicanes. Engine mode and DRS efficiency matter more than downforce here.",
    predictionAngle: "The slipstream makes qualifying a lottery and the lead genuinely changeable, so don't over-trust pole (only ~55% convert). Look for the strongest race-pace car and remember a chicane-triggered safety car can reshuffle the podium.",
  },
  {
    round: 14,
    trackType: "Street",
    overtaking: "Occasional",
    overtakingNote: "Early indications suggest the Madrid layout has long straights with DRS zones to promote overtaking.",
    safetyCarLikelihood: "High",
    safetyCarNote: "Brand-new street circuits typically see incidents in the early laps as drivers learn the walls.",
    poleToWinPct: 65,
    poleToWinNote: "No historical data — track position is usually key on debut street circuits.",
    insight: "Madrid joins the F1 calendar in 2026 for the first time, replacing the old Valencia Street Circuit that ran 2008–2012.",
    hasHistory: false,
    tyreStops: "Unknown",
    tyreNote: "A brand-new hybrid street/permanent layout with no historical tyre data, plus a banked corner unlike anything else on the calendar. Practice pace and long-run deg from Friday will be the only reliable guide — treat any strategy read as provisional.",
    weatherNote: "Mid-September Madrid is typically hot and dry with low rain risk, so high track temperatures and tyre warm-up should be the bigger factor than precipitation.",
    trackFavours: "Impossible to call precisely on debut, but the mix of long straights and a technical middle sector should reward an adaptable, well-rounded car and drivers quick to learn the limits.",
    predictionAngle: "No historical data means high uncertainty — lean on Friday practice pace rather than the form book. On unfamiliar circuits track position and clean weekends dominate, so favour whoever qualifies well and keeps it off the walls.",
  },
  {
    round: 15,
    trackType: "Street",
    overtaking: "Occasional",
    overtakingNote: "The long front straight and castle section hairpin are the prime overtaking zones under DRS.",
    safetyCarLikelihood: "High",
    safetyCarNote: "Baku is famous for late-race drama — safety cars appear almost every year at the castle section.",
    poleToWinPct: 60,
    poleToWinNote: "Safety-car restarts frequently create chaos and can promote back-of-grid runners to surprise podiums.",
    insight: "Baku's castle section is the tightest part of any F1 circuit at just 7.6 m wide — a single car's width.",
    hasHistory: true,
    tyreStops: "1-stop",
    tyreNote: "Smooth surface and long full-throttle sections mean low tyre degradation and a comfortable 1-stop, but a near-inevitable safety car often gifts a 'free' pit stop that rewards whoever gambles on staying out or boxing early.",
    weatherNote: "Late-September Baku is warm and dry, with Caspian Sea crosswinds the main variable — gusts down the 2.2 km straight unsettle braking into Turn 1 and cause lock-ups.",
    trackFavours: "Low-drag setups with strong straight-line speed and traction out of the 90-degree corners. A brave, precise driver through the castle section is worth several tenths.",
    predictionAngle: "Expect drama: a safety car is almost a certainty and the enormous slipstream makes both qualifying and the race unpredictable. Pole converts only ~60% of the time, and surprise poles or podiums from midfield cars are a recurring Baku theme.",
  },
  {
    round: 16,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "The long back straight into a hard-braking hairpin is a proven passing zone, backed up by two further DRS chances.",
    safetyCarLikelihood: "High",
    safetyCarNote: "Sudden tropical downpours are the defining feature of racing at Sepang — they've triggered red flags and safety cars for years.",
    poleToWinPct: 55,
    poleToWinNote: "No 2024/2025 form to lean on — Sepang last hosted F1 in 2017, before this grid's core lineup arrived.",
    insight: "Malaysia hosts this race under the Bahrain Grand Prix name and branding after Bahrain's own event couldn't be held — Sepang last held an F1 race in 2017.",
    hasHistory: false,
    tyreStops: "Unknown",
    tyreNote: "No recent tyre data from this compound generation. Historically Sepang's abrasive surface and heavy, sustained-load corners produced some of the highest degradation on the calendar — expect strategy to be reactive rather than pre-planned.",
    weatherNote: "Equatorial heat and humidity, with a real chance of a violent afternoon thunderstorm interrupting the session — this was a recurring storyline in Sepang's earlier F1 years.",
    trackFavours: "Cars with strong high-speed cornering stability and good cooling in oppressive heat and humidity. Confidence in mixed or drying conditions is a genuine advantage here.",
    predictionAngle: "This is a genuine unknown on the 2026 calendar — no current-grid form, no recent tyre or setup data. Weight Friday practice heavily, and treat a weather-driven upset as a real possibility rather than a long shot.",
  },
  {
    round: 17,
    trackType: "Street",
    overtaking: "Rare",
    overtakingNote: "Narrow sections and slow corners limit passing; strategy and tyre management decide most outcomes.",
    safetyCarLikelihood: "High",
    safetyCarNote: "Night racing on a street circuit with no run-off means the safety car appears at almost every Singapore GP.",
    poleToWinPct: 75,
    poleToWinNote: "Qualifying lap is almost as decisive as Monaco — track position is the race strategy.",
    insight: "Singapore is the only night race in Formula 1, with over 1,500 lights illuminating the 5.063 km circuit.",
    hasHistory: true,
    tyreStops: "1–2 stop",
    tyreNote: "Constant traction events and stifling humidity load the tyres and the drivers, keeping degradation on the higher side. A safety car is so likely that teams plan around a cheap stop, which pushes many toward a reactive 1-stop.",
    weatherNote: "Hot and extremely humid even at night, and tropical downpours are a real evening threat — rain on this walled circuit would massively raise the chaos factor.",
    trackFavours: "High-downforce cars with strong traction and good braking stability, plus physically resilient drivers — Singapore is the most demanding race of the year on fitness and concentration.",
    predictionAngle: "It's a Sprint weekend AND a track where overtaking is brutally hard, so qualifying position (pole wins ~75%) is the dominant signal for both races. Bank on a safety car, and treat any rain forecast as a green light for an upset.",
  },
  {
    round: 18,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "Long straights and Turn 1 / Turn 12 hairpins offer repeated passing opportunities each lap.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "Austin crowds and changeable Texas weather can contribute to incidents — SC appearance is roughly 50/50.",
    poleToWinPct: 60,
    poleToWinNote: "Multiple DRS zones make overtaking easier than most circuits; strategy is often the decider.",
    insight: "The circuit's layout was inspired by multiple famous F1 corners — Turn 1 mimics Istanbul Park's Turn 8.",
    hasHistory: true,
    tyreStops: "1–2 stop",
    tyreNote: "A famously bumpy, subsidence-affected surface combined with fast direction changes in the esses produces medium-to-high degradation, so both 1- and 2-stop strategies are viable and can diverge between the front-runners.",
    weatherNote: "Late-October Texas is unpredictable — warm and dry one year, cold and stormy the next. Big temperature swings between sessions change tyre warm-up and the strategy picture.",
    trackFavours: "Cars with a compliant ride over bumps and strong high-speed change of direction through the Sector 1 esses. Good traction out of the Sector 3 hairpins also pays off under DRS.",
    predictionAngle: "Real overtaking is possible here, so pole is less decisive (~60%) and strategy frequently decides it — look for the best race-pace car rather than just the fastest qualifier. The bumps punish stiff setups, occasionally catching out a favourite.",
  },
  {
    round: 19,
    trackType: "Permanent",
    overtaking: "Occasional",
    overtakingNote: "The long main straight and Peraltada give DRS a boost, but the stadium section limits passing.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "High altitude affects engine power and tyre behaviour, contributing to more incidents than expected.",
    poleToWinPct: 65,
    poleToWinNote: "Pole sitter takes a very clean line into Turn 1 — the bumpy track punishes those who lose that early position.",
    insight: "Mexico City sits at 2,240 m above sea level — the highest altitude of any F1 circuit.",
    hasHistory: true,
    tyreStops: "1-stop",
    tyreNote: "Thin air means low aero grip and low tyre-energy loading, so degradation is genuinely low and a 1-stop is standard. The bigger challenge is getting tyres up to temperature and managing brake and engine cooling in the altitude.",
    weatherNote: "Usually mild and dry in early November, so weather rarely intervenes. The altitude, not the sky, is the defining condition — it saps power and cooling all weekend.",
    trackFavours: "Cars with efficient cooling and strong downforce that works in thin air, plus good traction. Teams that nail the enormous run to Turn 1 gain places off the line.",
    predictionAngle: "The long, wide sprint to Turn 1 makes the start pivotal and rewards pole (~65%), but low grip means overtaking into the stadium section is tough. Watch for cooling struggles — a car marginal on temperatures can quietly fade.",
  },
  {
    round: 20,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "Interlagos is a short, flowing circuit; lapped traffic and DRS zones create frequent action.",
    safetyCarLikelihood: "High",
    safetyCarNote: "Unpredictable São Paulo weather — often sudden downpours — triggers safety cars with remarkable regularity.",
    poleToWinPct: 50,
    poleToWinNote: "Brazilian GPs have high safety-car frequency, rain risk, and short straights — anything can happen.",
    insight: "Interlagos runs anticlockwise — one of only four circuits on the calendar to do so.",
    hasHistory: true,
    tyreStops: "1–2 stop",
    tyreNote: "A short, flowing anticlockwise lap gives moderate degradation, but the real strategy driver is weather — teams must stay flexible because a shower can turn a 1-stop into a scramble for intermediates at any moment.",
    weatherNote: "The single most changeable forecast on the calendar. Sudden São Paulo downpours arrive with little warning and have decided championships — high rain risk is baked into every prediction here.",
    trackFavours: "Wet-weather aces and cars with strong mechanical grip and traction for the twisty final sector. Bravery and adaptability matter more than outright dry-lap pace.",
    predictionAngle: "The highest chaos factor of the year — pole converts only ~50%, safety cars are frequent, and rain can strike at any time. Favour proven wet-weather drivers, expect surprises, and treat safety-car picks as strong value.",
  },
  {
    round: 21,
    trackType: "Street",
    overtaking: "Frequent",
    overtakingNote: "The 1.9 km Strip straight gives cars one of the longest DRS runs in F1 — overtaking is common.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "Inexperienced night-time street circuit with cold track temperatures leads to occasional incidents.",
    poleToWinPct: 55,
    poleToWinNote: "The sheer length of the straight means faster cars can attack from well behind under DRS.",
    insight: "Las Vegas returns to F1 for the first time since the 1982 Caesars Palace Grand Prix, which used a car park layout.",
    hasHistory: true,
    tyreStops: "1-stop",
    tyreNote: "The story here is cold, not wear — very low track temperatures on the long straights make tyre warm-up and graining the dominant concern. Degradation is low, so it's a 1-stop, but getting heat into the tyres for a qualifying lap or a restart is the real puzzle.",
    weatherNote: "A cold desert night with track temps that can drop into single digits. No rain concern, but the cold makes warm-up, braking, and out-lap tyre prep decisive.",
    trackFavours: "Low-drag cars with strong straight-line speed that can also switch tyres on quickly in the cold. Traction out of the slow corners onto the long straights is key.",
    predictionAngle: "The 1.9 km straight makes overtaking easy, so pole is worth less than usual (~55%) and a fast car can win from off the front row. The wildcard is tyre warm-up in the cold — whoever masters it in qualifying and on restarts holds the edge.",
  },
  {
    round: 22,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "Lusail's smooth surface and multiple long straights give DRS maximum effect for passing.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "Night racing under lights on a relatively new circuit — gravel and incidents are part of the challenge.",
    poleToWinPct: 65,
    poleToWinNote: "Pole sitters have a clear track and rarely face pressure in the opening phase of the race.",
    insight: "Qatar's Losail circuit was a motorbike venue for 20 years before Formula 1 visited for the first time in 2021.",
    hasHistory: true,
    tyreStops: "2–3 stop",
    tyreNote: "The wall of fast, flowing corners puts extreme energy through the tyres — so much that the FIA has previously imposed maximum stint lengths, forcing a mandatory multi-stop. Expect a busy, strategy-heavy race rather than a one-stop cruise.",
    weatherNote: "A warm, dry desert night under lights — rain is a non-factor. Track temperature drop through the evening and wind-blown sand are the only real variables.",
    trackFavours: "Cars that are kind to their tyres through sustained high-speed loading, with strong aero through medium-fast corners. Tyre management discipline is worth more here than at almost any other track.",
    predictionAngle: "Forget the usual conservative strategy — enforced short stints mean 2–3 stops and plenty of on-track movement, so race pace and tyre life matter more than pure qualifying position. Favour cars that historically look after their rubber.",
  },
  {
    round: 23,
    trackType: "Permanent",
    overtaking: "Occasional",
    overtakingNote: "DRS on the long main straight helps, but the tight hairpin and narrow sections limit other opportunities.",
    safetyCarLikelihood: "Low",
    safetyCarNote: "Yas Marina is a smooth, modern circuit designed with run-off — safety cars appear infrequently.",
    poleToWinPct: 65,
    poleToWinNote: "Pole is useful, but softer compounds under Abu Dhabi's lights often produce engaging strategy battles.",
    insight: "The Abu Dhabi GP is always the final race of the season — its floodlit circuit was designed by Hermann Tilke.",
    hasHistory: true,
    tyreStops: "1-stop",
    tyreNote: "A smooth surface and moderate corner loads keep degradation low, making a 1-stop the default. Softer compound allocations in recent years have occasionally opened the door to a two-stop offset, but strategy variance stays modest.",
    weatherNote: "A warm, dry evening race that starts in daylight and finishes under lights, so track temperature falls through the race — a stable, low-risk forecast with no rain concern.",
    trackFavours: "Well-balanced cars with good traction out of the slow final sector and efficient braking into the hairpins. A clean, controlled weekend beats gambling on this predictable layout.",
    predictionAngle: "The lowest-variance race on the calendar and the season finale — track position holds up well (pole ~65%) and safety cars are rare. Trust the form book and qualifying order here more than almost anywhere; big upsets are uncommon.",
  },
];
