export interface CircuitCharacter {
  round: number;
  trackType: "Street" | "Permanent";
  overtaking: "Rare" | "Occasional" | "Frequent";
  overtakingNote: string;
  safetyCarLikelihood: "Low" | "Medium" | "High";
  safetyCarNote: string;
  poleToWinPct: number;
  poleToWinNote: string;
  insight: string;
  hasHistory: boolean;
}

export const CIRCUIT_INTEL: CircuitCharacter[] = [
  {
    round: 1,
    trackType: "Permanent",
    overtaking: "Occasional",
    overtakingNote: "Turn 1 and Turn 9 chicane offer the best passing chances, but tyre delta is often needed.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "Walls are close at some corners and the field is bunched after the restart — incidents happen.",
    poleToWinPct: 60,
    poleToWinNote: "Pole converts to victory about 60% of the time; the long run to Turn 1 keeps challengers honest.",
    insight: "Albert Park hosted an F1 race for the first time in 1996, and Michael Schumacher won that inaugural event.",
    hasHistory: true,
  },
  {
    round: 2,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "Long straights into Turns 6 and 14 give DRS a full effect and generate multiple passes per lap.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "High-speed corners and a long back section create occasional contact, especially at the start.",
    poleToWinPct: 65,
    poleToWinNote: "Pole is valuable on the long run to Turn 1, giving pole sitters a strong conversion rate.",
    insight: "Shanghai hosted the first ever Chinese Grand Prix in 2004 — Michael Schumacher won that race too.",
    hasHistory: true,
  },
  {
    round: 3,
    trackType: "Permanent",
    overtaking: "Occasional",
    overtakingNote: "The Esses demand focus, not overtaking; Degner and the Spoon curve offer the real attack points.",
    safetyCarLikelihood: "Low",
    safetyCarNote: "Suzuka is wide and forgiving enough that big incidents are rare despite its fearsome reputation.",
    poleToWinPct: 70,
    poleToWinNote: "Qualifying pace is decisive — once through the Esses cleanly, a fast car is very hard to pass.",
    insight: "Suzuka is one of only two figure-eight circuits on the F1 calendar, with the overpass unique in motorsport.",
    hasHistory: true,
  },
  {
    round: 4,
    trackType: "Permanent",
    overtaking: "Occasional",
    overtakingNote: "Turn 4 and Turn 11 see most passes, aided by DRS, but clean air advantage limits battles.",
    safetyCarLikelihood: "Low",
    safetyCarNote: "Wide run-off areas and a smooth surface mean most mistakes end in the gravel rather than a safety car.",
    poleToWinPct: 65,
    poleToWinNote: "Pole is useful but not decisive — tyre management and strategy can reshuffle the order.",
    insight: "Bahrain was the first Middle-Eastern country to host a Formula 1 Grand Prix, starting in 2004.",
    hasHistory: true,
  },
  {
    round: 5,
    trackType: "Street",
    overtaking: "Occasional",
    overtakingNote: "The long front straight rewards DRS, but narrow sections and barriers limit most other attack zones.",
    safetyCarLikelihood: "High",
    safetyCarNote: "Jeddah's barriers are millimetres from the racing line — any contact immediately brings out the safety car.",
    poleToWinPct: 75,
    poleToWinNote: "Qualifying position is critical here; passing is genuinely difficult so track position is everything.",
    insight: "Jeddah is the fastest street circuit in F1 history, with average lap speeds above 250 km/h.",
    hasHistory: true,
  },
  {
    round: 6,
    trackType: "Street",
    overtaking: "Occasional",
    overtakingNote: "Two DRS zones help, but the tight infield limits overtaking to Turn 1 and the final hairpin.",
    safetyCarLikelihood: "High",
    safetyCarNote: "Racing through a car park on a temporary circuit means the safety car makes multiple appearances most years.",
    poleToWinPct: 60,
    poleToWinNote: "Sprint weekend format shuffles the grid, often making the Sunday race more chaotic than pole suggests.",
    insight: "The Miami GP venue is built around Hard Rock Stadium — drivers actually race through a faux marina never used for boats.",
    hasHistory: true,
  },
  {
    round: 7,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "Multiple hairpins and a long pit straight with DRS create consistent overtaking opportunities.",
    safetyCarLikelihood: "High",
    safetyCarNote: "Unpredictable Montreal weather and the Wall of Champions claim victims almost every year.",
    poleToWinPct: 55,
    poleToWinNote: "Strategy and safety-car restarts regularly upset the running order, making pole less dominant.",
    insight: "The notorious 'Wall of Champions' at the final chicane has caught Damon Hill, Michael Schumacher, and Jacques Villeneuve.",
    hasHistory: true,
  },
  {
    round: 8,
    trackType: "Street",
    overtaking: "Rare",
    overtakingNote: "Monaco is the hardest circuit in the world to overtake on — strategy and qualifying almost entirely decide it.",
    safetyCarLikelihood: "High",
    safetyCarNote: "Any touch of the barrier brings out the safety car; a virtual safety car appears on the vast majority of Sundays.",
    poleToWinPct: 80,
    poleToWinNote: "Pole position is more valuable here than anywhere — Monaco is basically a time trial on Saturday.",
    insight: "Ayrton Senna won 6 Monaco GPs. His 1984 drive in the rain — before retirement — is considered his greatest lap.",
    hasHistory: true,
  },
  {
    round: 9,
    trackType: "Permanent",
    overtaking: "Occasional",
    overtakingNote: "Long lap 1 into Turn 1, plus the final chicane, are the main passing spots on this technical circuit.",
    safetyCarLikelihood: "Low",
    safetyCarNote: "Wide run-off areas and modern barriers keep incidents contained — safety cars are genuinely rare here.",
    poleToWinPct: 65,
    poleToWinNote: "Tyre management matters as much as raw pace — cars degrade heavily in the heat.",
    insight: "Barcelona was a key testing venue for decades, meaning teams knew every bump before the season even started.",
    hasHistory: true,
  },
  {
    round: 10,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "The short layout and multiple DRS zones make overtaking common, especially after safety-car restarts.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "High-speed corners and close racing create regular incidents, particularly in wet Austrian conditions.",
    poleToWinPct: 60,
    poleToWinNote: "DRS is very effective here; a quicker car can pass even from a few places back.",
    insight: "The Red Bull Ring is one of the shortest F1 circuits, meaning drivers complete more laps than anywhere else on the calendar.",
    hasHistory: true,
  },
  {
    round: 11,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "Copse, Maggotts and the Hangar straight all provide overtaking chances; British fans are treated to great racing.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "Changeable British weather can trigger incidents, and high-speed corners increase risk on the opening lap.",
    poleToWinPct: 60,
    poleToWinNote: "Strategy plays a significant role — tyre choices in variable conditions can completely change the result.",
    insight: "Silverstone hosted the very first Formula 1 World Championship race in 1950, making it F1's spiritual home.",
    hasHistory: true,
  },
  {
    round: 12,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "Raidillon-Kemmel and the Bus Stop chicane are both overtaking hotspots on this mega-fast circuit.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "Weather in the Ardennes changes rapidly — fog, rain, and poor visibility have forced red flags and delays.",
    poleToWinPct: 60,
    poleToWinNote: "Spa rewards pure downforce and power, so race pace can differ wildly depending on power unit spec.",
    insight: "Spa-Francorchamps is the longest circuit on the F1 calendar at 7.004 km per lap.",
    hasHistory: true,
  },
  {
    round: 13,
    trackType: "Permanent",
    overtaking: "Rare",
    overtakingNote: "The twisty, narrow Hungaroring offers very few clean passing opportunities — it's called the Monaco of permanent tracks.",
    safetyCarLikelihood: "Low",
    safetyCarNote: "Relatively modern surface and wide run-offs keep the safety car in the garage most Sundays.",
    poleToWinPct: 75,
    poleToWinNote: "Overtaking is so difficult that qualifying position can define the entire race outcome.",
    insight: "Hungary hosted the first F1 race behind the Iron Curtain in 1986, drawing 200,000 spectators.",
    hasHistory: true,
  },
  {
    round: 14,
    trackType: "Permanent",
    overtaking: "Occasional",
    overtakingNote: "Tarzanbocht hairpin and the final chicane see most passes, though wind direction can change everything.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "Sand blown onto the track from the dunes and unpredictable sea wind cause frequent incidents.",
    poleToWinPct: 65,
    poleToWinNote: "Zandvoort is tight and fast; once settled, leading cars rarely face serious pressure.",
    insight: "Zandvoort was absent from the F1 calendar for 35 years before returning as the Dutch GP home in 2021.",
    hasHistory: true,
  },
  {
    round: 15,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "Monza has the highest top speeds in F1; the long straights and chicanes generate huge slipstreaming battles.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "The chicanes cause contact at high approach speeds, and tyre failures are a historical risk.",
    poleToWinPct: 55,
    poleToWinNote: "Slipstreaming means the lead changes multiple times per lap; qualifying matters but race pace and strategy rule.",
    insight: "Monza is the fastest circuit in F1, regularly seeing average race speeds above 260 km/h.",
    hasHistory: true,
  },
  {
    round: 16,
    trackType: "Street",
    overtaking: "Occasional",
    overtakingNote: "Early indications suggest the Madrid layout has long straights with DRS zones to promote overtaking.",
    safetyCarLikelihood: "High",
    safetyCarNote: "Brand-new street circuits typically see incidents in the early laps as drivers learn the walls.",
    poleToWinPct: 65,
    poleToWinNote: "No historical data — track position is usually key on debut street circuits.",
    insight: "Madrid joins the F1 calendar in 2026 for the first time, replacing the old Valencia Street Circuit that ran 2008–2012.",
    hasHistory: false,
  },
  {
    round: 17,
    trackType: "Street",
    overtaking: "Occasional",
    overtakingNote: "The long front straight and castle section hairpin are the prime overtaking zones under DRS.",
    safetyCarLikelihood: "High",
    safetyCarNote: "Baku is famous for late-race drama — safety cars appear almost every year at the castle section.",
    poleToWinPct: 60,
    poleToWinNote: "Safety-car restarts frequently create chaos and can promote back-of-grid runners to surprise podiums.",
    insight: "Baku's castle section is the tightest part of any F1 circuit at just 7.6 m wide — a single car's width.",
    hasHistory: true,
  },
  {
    round: 18,
    trackType: "Street",
    overtaking: "Rare",
    overtakingNote: "Narrow sections and slow corners limit passing; strategy and tyre management decide most outcomes.",
    safetyCarLikelihood: "High",
    safetyCarNote: "Night racing on a street circuit with no run-off means the safety car appears at almost every Singapore GP.",
    poleToWinPct: 75,
    poleToWinNote: "Qualifying lap is almost as decisive as Monaco — track position is the race strategy.",
    insight: "Singapore is the only night race in Formula 1, with over 1,500 lights illuminating the 5.063 km circuit.",
    hasHistory: true,
  },
  {
    round: 19,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "Long straights and Turn 1 / Turn 12 hairpins offer repeated passing opportunities each lap.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "Austin crowds and changeable Texas weather can contribute to incidents — SC appearance is roughly 50/50.",
    poleToWinPct: 60,
    poleToWinNote: "Multiple DRS zones make overtaking easier than most circuits; strategy is often the decider.",
    insight: "The circuit's layout was inspired by multiple famous F1 corners — Turn 1 mimics Istanbul Park's Turn 8.",
    hasHistory: true,
  },
  {
    round: 20,
    trackType: "Permanent",
    overtaking: "Occasional",
    overtakingNote: "The long main straight and Peraltada give DRS a boost, but the stadium section limits passing.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "High altitude affects engine power and tyre behaviour, contributing to more incidents than expected.",
    poleToWinPct: 65,
    poleToWinNote: "Pole sitter takes a very clean line into Turn 1 — the bumpy track punishes those who lose that early position.",
    insight: "Mexico City sits at 2,240 m above sea level — the highest altitude of any F1 circuit.",
    hasHistory: true,
  },
  {
    round: 21,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "Interlagos is a short, flowing circuit; lapped traffic and DRS zones create frequent action.",
    safetyCarLikelihood: "High",
    safetyCarNote: "Unpredictable São Paulo weather — often sudden downpours — triggers safety cars with remarkable regularity.",
    poleToWinPct: 50,
    poleToWinNote: "Brazilian GPs have high safety-car frequency, rain risk, and short straights — anything can happen.",
    insight: "Interlagos runs anticlockwise — one of only four circuits on the calendar to do so.",
    hasHistory: true,
  },
  {
    round: 22,
    trackType: "Street",
    overtaking: "Frequent",
    overtakingNote: "The 1.9 km Strip straight gives cars one of the longest DRS runs in F1 — overtaking is common.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "Inexperienced night-time street circuit with cold track temperatures leads to occasional incidents.",
    poleToWinPct: 55,
    poleToWinNote: "The sheer length of the straight means faster cars can attack from well behind under DRS.",
    insight: "Las Vegas returns to F1 for the first time since the 1982 Caesars Palace Grand Prix, which used a car park layout.",
    hasHistory: true,
  },
  {
    round: 23,
    trackType: "Permanent",
    overtaking: "Frequent",
    overtakingNote: "Lusail's smooth surface and multiple long straights give DRS maximum effect for passing.",
    safetyCarLikelihood: "Medium",
    safetyCarNote: "Night racing under lights on a relatively new circuit — gravel and incidents are part of the challenge.",
    poleToWinPct: 65,
    poleToWinNote: "Pole sitters have a clear track and rarely face pressure in the opening phase of the race.",
    insight: "Qatar's Losail circuit was a motorbike venue for 20 years before Formula 1 visited for the first time in 2021.",
    hasHistory: true,
  },
  {
    round: 24,
    trackType: "Permanent",
    overtaking: "Occasional",
    overtakingNote: "DRS on the long main straight helps, but the tight hairpin and narrow sections limit other opportunities.",
    safetyCarLikelihood: "Low",
    safetyCarNote: "Yas Marina is a smooth, modern circuit designed with run-off — safety cars appear infrequently.",
    poleToWinPct: 65,
    poleToWinNote: "Pole is useful, but softer compounds under Abu Dhabi's lights often produce engaging strategy battles.",
    insight: "The Abu Dhabi GP is always the final race of the season — its floodlit circuit was designed by Hermann Tilke.",
    hasHistory: true,
  },
];
