export const DRIVER_IMAGES: Record<string, string> = {
  "max-verstappen":    "/images/drivers/JPG_RGB_72_DPI-f1_RB_M_Verstappen_1250.png",
  "isack-hadjar":      "/images/drivers/JPG_RGB_72_DPI-f1_Rb_I_Hadjar_1571.png",
  "lewis-hamilton":    "/images/drivers/JPG_RGB_72_DPI-f1_FER_L_Hamilton_0223.png",
  "charles-leclerc":   "/images/drivers/JPG_RGB_72_DPI-F1_FER_C_Leclerc_1421.png",
  "george-russell":    "/images/drivers/JPG_RGB_72_DPI-F1_Merc_G_Russell_0068.png",
  "kimi-antonelli":    "/images/drivers/JPG_RGB_72_DPI-F1_Merc_K_Antonelli_1442.png",
  "lando-norris":      "/images/drivers/JPG_RGB_72_DPI-F1_MCL_L_Norris_2551.png",
  "oscar-piastri":     "/images/drivers/JPG_RGB_72_DPI-F1_MCL_O_Piastri_1053.png",
  "fernando-alonso":   "/images/drivers/JPG_RGB_72_DPI-F1_Ast_F_Alonso_3069.png",
  "lance-stroll":      "/images/drivers/JPG_RGB_72_DPI-F1_Ast_L_Stroll_3399.png",
  "pierre-gasly":      "/images/drivers/JPG_RGB_72_DPI-f1_Alp_P_Gasly_3683.png",
  "franco-colapinto":  "/images/drivers/JPG_RGB_72_DPI-F1_Alp_F_Colapinto_0816.png",
  "carlos-sainz":      "/images/drivers/f1_Wil_C_Sainz_0490.png",
  "alexander-albon":   "/images/drivers/JPG_RGB_72_DPI-f1_Wil_A_Albon_0804.png",
  "nico-hulkenberg":   "/images/drivers/JPG_RGB_72_DPI-F1_Audi_N_Hulkenberg_1756.png",
  "gabriel-bortoleto": "/images/drivers/JPG_RGB_72_DPI-f1_Audi_G_Bortoleto_2348.png",
  "liam-lawson":       "/images/drivers/f1_Vcarb_L_Lawson_2229.png",
  "arvid-lindblad":    "/images/drivers/JPG_RGB_72_DPI-F1_Vcarb_A_Linblad_0487.png",
  "oliver-bearman":    "/images/drivers/JPG_RGB_72_DPI-f1_Haas_O_Bearman_1827.png",
  "esteban-ocon":      "/images/drivers/JPG_RGB_72_DPI-f1_Haas_E_Ocon_1077.png",
  "valtteri-bottas":   "/images/drivers/JPG_RGB_72_DPI-f1_CAD_V_Bottas_3029.png",
  "sergio-perez":      "/images/drivers/JPG_RGB_72_DPI-F1_CAD_S_Perez_2004.png",
};
